FROM openjdk:11.0.8-jdk-slim

COPY ./jitsi-videobridge /home/jitsi-videobridge
COPY ./jacocoagent.jar /usr/share/jitsi-videobridge/jacocoagent.jar

COPY ./jvb-for-coverage.sh /home/jitsi-videobridge/jvb.sh
ENTRYPOINT ["/home/jitsi-videobridge/jvb.sh"]